// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgdb

import (
	"context"
)

type Querier interface {
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateCategory(ctx context.Context, categoryName string) (Category, error)
	CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAppointment(ctx context.Context, arg DeleteAppointmentParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllAppointment(ctx context.Context) ([]Appointment, error)
	GetAllCategory(ctx context.Context) ([]Category, error)
	GetAllusers(ctx context.Context) ([]User, error)
	GetAppointmentDetails(ctx context.Context, id int64) (GetAppointmentDetailsRow, error)
	GetDoctorAppointment(ctx context.Context, doctorID int64) ([]Appointment, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	LoginUser(ctx context.Context, email string) (User, error)
	MyAppointment(ctx context.Context, usersID int64) ([]Appointment, error)
	SeeAllAppointmentByDoctorId(ctx context.Context, doctorID int64) ([]Appointment, error)
	SeeAllAppointmentByUserId(ctx context.Context, usersID int64) ([]Appointment, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
